
server:
  port: 8999

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:9001/user
          predicates:
            - Path=/user/**
        - id: contact-service
          uri: http://localhost:9002
          predicates:
            - Path=/contact/**